### ISSUE TITLE
Add "Lines" to navbar

### ISSUE THREAD

**Issue by sabrinazhai** [lunar-gala/2021-eusociality#67]
Add "Lines" to the desktop navbar. When entering landing page / home page, "lines" is already active. Clicking on it whilst it's active will not do anything. On other pages, works the same way clicking on "Collectiva" does now.
![image](https://user-images.githubusercontent.com/18226249/111851752-bd46ac80-88d1-11eb-9184-3e3a05a25f4a.png)

**Comment by mikinty** [comment]
Resolved by #70
