### ISSUE TITLE
Place lines + frames on top of photos

### ISSUE THREAD

**Issue by sabrinazhai** [lunar-gala/2021-eusociality#68]
The top line and the picture frame lines should be on top of the photos rather than under.
Currently:
![image](https://user-images.githubusercontent.com/18226249/111851799-e6673d00-88d1-11eb-9271-503a6ec95c32.png)

Supposed to be: 
![image](https://user-images.githubusercontent.com/18226249/111851823-fbdc6700-88d1-11eb-9c56-64f55efb1024.png)

**Comment by mikinty** [comment]
Update, @sabrinazhai  would prefer offset photos so we don't have to worry about aligning perfectly to the designer line

![image](https://user-images.githubusercontent.com/12106484/111916635-3ec54880-8a52-11eb-95ea-2da11e6a07e8.png)

**Comment by mikinty** [comment]
Will be fixed in #70
